# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kalyan', '0002_auto_20170812_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_logged_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
