# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalyan', '0003_auto_20170812_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_logged_in',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
