# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalyan', '0004_auto_20170812_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='num_complains',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='num_suggestions',
            field=models.IntegerField(default=0),
        ),
    ]
