# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalyan', '0007_remove_complains_many_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complains',
            name='many_profile',
        ),
    ]
