# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalyan', '0008_remove_complains_many_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestions',
            name='many_category',
        ),
        migrations.RemoveField(
            model_name='suggestions',
            name='many_profile',
        ),
    ]
