# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalyan', '0010_auto_20170814_0351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complains',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='suggestions',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='many_profile',
        ),
    ]
