# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalyan', '0012_auto_20170815_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='complains',
            options={'ordering': ['-created_on'], 'verbose_name': 'Complain', 'verbose_name_plural': 'Complains'},
        ),
        migrations.AlterModelOptions(
            name='suggestions',
            options={'ordering': ['-created_on'], 'verbose_name': 'Suggestion', 'verbose_name_plural': 'Suggestions'},
        ),
        migrations.AddField(
            model_name='complains',
            name='ulocation',
            field=models.CharField(default='Location Not known', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='cname',
            field=models.CharField(max_length=50, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='complains',
            name='complain_for',
            field=models.CharField(max_length=50, verbose_name='Complain For'),
        ),
        migrations.AlterField(
            model_name='complains',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='complains',
            name='subject',
            field=models.CharField(default='Complain', max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='complains',
            name='ucomplain',
            field=models.TextField(max_length=500, verbose_name='Complain'),
        ),
        migrations.AlterField(
            model_name='complains',
            name='uname',
            field=models.CharField(max_length=50, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feed',
            field=models.TextField(max_length=500, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='uname',
            field=models.CharField(max_length=50, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bcardid',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_logged_in',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Login Time'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uname',
            field=models.CharField(max_length=50, unique=True, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.BooleanField(default=False, verbose_name='Government Official'),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='subject',
            field=models.CharField(default='Suggestion', max_length=30, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='suggest_for',
            field=models.CharField(max_length=50, verbose_name='Suggestion For'),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='uname',
            field=models.CharField(max_length=50, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='usuggestion',
            field=models.TextField(max_length=500, verbose_name='Suggestion'),
        ),
    ]
