# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalyan', '0013_auto_20170816_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('app_name', models.CharField(default='Application', max_length=100, verbose_name='Application name')),
                ('app_desc', models.TextField(max_length=500, verbose_name='Application Description')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='num_complains',
        ),
        migrations.RemoveField(
            model_name='category',
            name='num_suggestions',
        ),
    ]
