# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalyan', '0014_auto_20170818_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Application', max_length=100, verbose_name='Application name')),
                ('app_desc', models.TextField(max_length=500, verbose_name='Application Description')),
            ],
            options={
                'verbose_name': 'AppCategory',
                'verbose_name_plural': 'AppCategory',
            },
        ),
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ['-created_on'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.RemoveField(
            model_name='applications',
            name='app_desc',
        ),
        migrations.AlterField(
            model_name='applications',
            name='app_name',
            field=models.CharField(default='application', max_length=50),
        ),
    ]
